# frozen_string_literal: true

source 'https://rubygems.org'
ruby '2.7.1'

gem 'web_pipe', '~> 0.12.1'
gem 'dry-schema', '~> 1.5'
gem 'hanami-router', '~> 1.3'
gem 'dry-transformer', '~> 0.1.1'
gem 'rack', '~> 2.2'
gem 'rerun', '~> 0.13'
gem 'puma', '~> 5.1'
